import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"


const poppins = Poppins({
  subsets: ['latin'],
   weight: ['100','200','300','400','500','600','700','800','900',] // Specify the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={poppins.className}
      >
        <Provider>
          {children}
           
        </Provider>
        <Toaster></Toaster>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
